name: Bug Report
description: Report a bug or broken feature
labels:
  - bug
body:
  - type: checkboxes
    id: duplicate
    attributes:
      label: Important First Steps
      description: >-
        Make sure you have checked these things before submitting your bug
        report
      options:
        - label: >-
            I have searched through the existing issues to make sure this is not
            a duplicate of another issue
          required: true
        - label: >-
            I have made sure that I am not running a newer version of Spotify
            that the latest supported version listed in the readme?
          required: true
  - type: input
    id: spotify_plus_version
    attributes:
      label: Spotify Plus Version
      placeholder: v0.7.0
    validations:
      required: true
  - type: input
    id: spotify_version
    attributes:
      label: Spotify Version
      placeholder: v9.1.62.1589
    validations:
      required: true
  - type: textarea
    id: bug_info
    attributes:
      label: What is the bug?
      description: What is the bug you found? Try to be as specific as youcan
      placeholder: Explain the bug...
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: How did you cause this bug?
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
        4. Step four
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste any logcat logs. This is probably the most helpful thing!
      render: text
