name: Feature Request
description: Suggest a new feature for Spotify Plus
labels:
  - enhancement
body:
  - type: checkboxes
    id: duplicate
    attributes:
      label: Important First Step
      description: "Make sure you have checked if there are any dupliates before submitting "
      options:
        - label: >-
            I have searched through the existing issues to make sure this is not
            a duplicate of another issue
          required: true
  - type: textarea
    id: feature_info
    attributes:
      label: What is the feature
      description: >-
        What would you like to see added to Spotify Plus? Try to be as specific
        as possible. The more specific, the better I can try to add it!
      placeholder: Explain the feature...
    validations:
      required: true
  - type: textarea
    id: why_is_your_feature_useful_bruh
    attributes:
      label: Why is this feature useful?
      description: Explain how this feature would be used, how would this benefit users?
      placeholder: Explain your feature's use case...
    validations:
      required: true
  - type: textarea
    id: additional_details
    attributes:
      label: Additional details
      description: >-
        Have any other information or details? Pictures or screenshots? Other
        products that are similar to what you're suggesting?
      render: text
